### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by jsjs2009** [Yusufma03/pfrnns#1]
Thank you for sharing your source code. May I ask whether you use Torch or Pytorch?

**Comment by Yusufma03** [comment]
Hey there! I was using PyTorch 1.3.1 for this project. You could simply create a virtual env and install all dependencies with
```
pip install -r requirements.txt
```

**Comment by jsjs2009** [comment]
Thanks for your guide!

**Comment by Yusufma03** [comment]
Sure, no worries :) I'll close the issue.
