### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by xuyin218** [Yusufma03/pfrnns#2]
Hello! I'm sorry to disturb you. I want to know how to use this paper for sequence prediction such as time-series . Can you show some code? Thank you very much!

**Comment by Yusufma03** [comment]
Hey there! In fact, my code provided does the sequential robot localization, which is exactly a sequence prediction task. 

For a general sequence prediction task, you might want to first encode the inputs into embedding vectors (see [here](https://github.com/Yusufma03/pfrnns/blob/7a42cb36702fe734d6b8f6d9b8209dca5f82419c/model.py#L117)). Next, we recursively run the PF-RNN over the entire time series (see [here](https://github.com/Yusufma03/pfrnns/blob/7a42cb36702fe734d6b8f6d9b8209dca5f82419c/model.py#L139)). In the end, you may want to do the prediction (see [here](https://github.com/Yusufma03/pfrnns/blob/7a42cb36702fe734d6b8f6d9b8209dca5f82419c/model.py#L155)).

Specifically for time series prediction, you could treat x{t+1} as the output given history x{1:t}, then use the difference between predicted \hat{x}{t+1} and x{t+1} as the loss function.

Please let me know if you have further questions.

**Comment by xuyin218** [comment]
> Hey there! In fact, my code provided does the sequential robot localization, which is exactly a sequence prediction task.
> 
> For a general sequence prediction task, you might want to first encode the inputs into embedding vectors (see [here](https://github.com/Yusufma03/pfrnns/blob/7a42cb36702fe734d6b8f6d9b8209dca5f82419c/model.py#L117)). Next, we recursively run the PF-RNN over the entire time series (see [here](https://github.com/Yusufma03/pfrnns/blob/7a42cb36702fe734d6b8f6d9b8209dca5f82419c/model.py#L139)). In the end, you may want to do the prediction (see [here](https://github.com/Yusufma03/pfrnns/blob/7a42cb36702fe734d6b8f6d9b8209dca5f82419c/model.py#L155)).
> 
> Specifically for time series prediction, you could treat x{t+1} as the output given history x{1:t}, then use the difference between predicted \hat{x}{t+1} and x{t+1} as the loss function.
> 
> Please let me know if you have further questions.

Thank you very much！！！My code is very poor, so I have to  study you code for a long time. Then I will try to achieve time series prediction according to your guidance. I hope I can do it. Maybe ........

**Comment by Yusufma03** [comment]
No worries. Just code more and it will improve haha. Issue closed.
