### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by xuyin218** [Yusufma03/pfrnns#3]
I'm sorry to disturb you again, I encountered some problems in the process of writing my code but I don't know how to solve it. So, I would like consult you:
1、Model.py: In "Localizer" class, "map_size” means maze size?
2、forward(self,map_in, obs_in, act_in): "map_in","obs_in","act_in"means?
3、I want to predict time-series, now do I need the function "step(self, map_in, obs_in, act_in, gt_pos, args)" ?
Thank you very much! Best Regards.

**Comment by Yusufma03** [comment]
No worries. 

>  1、Model.py: In "Localizer" class, "map_size” means maze size?

Yes. 

>  2、forward(self,map_in, obs_in, act_in): "map_in","obs_in","act_in"means?

These are the input sequences, where map_in stands for the maze, obs_in is the local observation the robot receives, and act_in corresponds to the actions chosen. 

>  3、I want to predict time-series, now do I need the function "step(self, map_in, obs_in, act_in, gt_pos, args)" ?

In my setup, yes. 

However, if you are not familiar with deep learning and time series modeling yet, I would recommend you to start with some general time series modeling tutorials first. For example, the classic but useful [ARIMA model](https://machinelearningmastery.com/arima-for-time-series-forecasting-with-python). If you plan to do deep learning, [this one](https://towardsdatascience.com/lstm-for-time-series-prediction-de8aeb26f2ca) explains how to code up an LSTM time series predictor step by step.

You can basically understand PF-RNNs as a variant of standard RNNs, e.g., LSTMs. Once you mastered the time series prediction using LSTM, then it becomes easy for you to use PF-RNNs.

**Comment by xuyin218** [comment]
> No worries.
> 
> > 1、Model.py: In "Localizer" class, "map_size” means maze size?
> 
> Yes.
> 
> > 2、forward(self,map_in, obs_in, act_in): "map_in","obs_in","act_in"means?
> 
> These are the input sequences, where map_in stands for the maze, obs_in is the local observation the robot receives, and act_in corresponds to the actions chosen.
> 
> > 3、I want to predict time-series, now do I need the function "step(self, map_in, obs_in, act_in, gt_pos, args)" ?
> 
> In my setup, yes.
> 
> However, if you are not familiar with deep learning and time series modeling yet, I would recommend you to start with some general time series modeling tutorials first. For example, the classic but useful [ARIMA model](https://machinelearningmastery.com/arima-for-time-series-forecasting-with-python). If you plan to do deep learning, [this one](https://towardsdatascience.com/lstm-for-time-series-prediction-de8aeb26f2ca) explains how to code up an LSTM time series predictor step by step.
> 
> You can basically understand PF-RNNs as a variant of standard RNNs, e.g., LSTMs. Once you mastered the time series prediction using LSTM, then it becomes easy for you to use PF-RNNs.

Thank you for your conscientious reply! Your advices are so useful! I think I must study the LSTM firstly, because I cannot understand some parts in your code. In you paper(AAAI2020), you said the PF-RNN model can predict stock price. Are you achieving it using python? how is the prediction accuracy? (Table 2 in you paper?) 
If you are willing to communicating with me, you can email to me.(xuyin218@mail.ustc.edu.cn)

**Comment by Yusufma03** [comment]
> Are you achieving it using python?

Yes. I used exactly my current PF-RNN implementation provided here. However, the training pipeline is different from the robot localization. Currently, I'm not considering to release other experiments.

> how is the prediction accuracy? (Table 2 in you paper?)

The prediction loss is given in the Table 1, NASDAQ entry.

**Comment by xuyin218** [comment]
> > Are you achieving it using python?
> 
> Yes. I used exactly my current PF-RNN implementation provided here. However, the training pipeline is different from the robot localization. Currently, I'm not considering to release other experiments.
> 
> > how is the prediction accuracy? (Table 2 in you paper?)
> 
> The prediction loss is given in the Table 1, NASDAQ entry.

Thank you for sharing the code of  the robot localization, otherwise I cannot know how to start. I can understand because writing codes is so hard!!! I will try to predict....

**Comment by Yusufma03** [comment]
No worries. Issue closed.
