### ISSUE TITLE
Why the code is running so slowly at the beginning?

### ISSUE THREAD

**Issue by KawhiZhao** [Yusufma03/pfrnns#8]
For the main.py, it takes a long time before training the 800 epochs (I think it's not because of the data preparation)

**Comment by Yusufma03** [comment]
Hi, could you provide more details about the issue? Do you mean that after the `eval data generated`, the progress bar is stuck for a while?

**Comment by KawhiZhao** [comment]
> Hi, could you provide more details about the issue? Do you mean that after the `eval data generated`, the progress bar is stuck for a while?

I think when running the training code, the program stucks for a while beforing loading the training data.

**Comment by KawhiZhao** [comment]
> > Hi, could you provide more details about the issue? Do you mean that after the `eval data generated`, the progress bar is stuck for a while?
> 
> I think when running the training code, the program stucks for a while beforing loading the training data.

<img width="1732" alt="Screen Shot 2021-07-17 at 11 08 42 AM" src="https://user-images.githubusercontent.com/44634290/126033568-89b61b90-75d7-46f4-9e45-b4edaf309727.png">
it stucks here a while before the progress bar appears

**Comment by Yusufma03** [comment]
I think this is actually normal. It takes time to load the pytorch runtime, and allocate GPU memory for the model and the tensors the first time we run it. Once this is done, that memory will be reused during the training.

**Comment by Yusufma03** [comment]
I'm closing the issue for now. Please feel free to reopen it if you have further questions.
